### ISSUE TITLE
Maven Dependency management of the JAR

### ISSUE THREAD

**Issue by M1dKn1gh7** [apemanzilla/edjournal#1]
I've a tried incorporating this code into a project I'm building myself however I'm having a lot of issues surrounding the downloading of the necessary JAR. The maven dependency tag as is does not seem to work (it does not appear on central) and the addition from bintray into the settings file did pull down gson and the other dependencies but not the core jar you need to compile the example code in the readme. 

Do you have a step by step set of instructions for this? or is there something I'm missing. The only thing that seemed to work was manually running the gradle builds and adding the JAR that way but that's not really an option for what I'm trying to do. having Maven manage the dependencies would be more ideal. 

I can give you more info if needed but any help is much appreciated. This library would be very useful for me.

Thanks!

**Comment by dmarcuse** [comment]
This project is mostly unmaintained now (I use Linux exclusively so can't run Elite: Dangerous), so I can't guarantee it still works. How does your build script compare to the [EDScan build script](https://github.com/apemanzilla/EDScan/blob/master/build.gradle)? Adding `jcenter()` to your repositories and then the dependency coordinates _should_ be sufficient, but I haven't used this in almost a year so something may have broken.

**Comment by dmarcuse** [comment]
When I have some free time, I can look into getting my Windows partition working again in case things still aren't working.

**Comment by M1dKn1gh7** [comment]
I appreciate you looking into it and replying :) I have retried it this evening and it seems to have pulled down the dependencies correctly and compiling. I don't know if you did anything between now and yesterday but if you did thank you. I added the maven tags as specified here: https://bintray.com/apemanzilla/maven/edjournal/1.2.0-beta2# and removed the <pom> tag. Seems to be ok now!

**Comment by dmarcuse** [comment]
I haven't changed anything, but glad to hear it's working now! Let me know if you need anything else.

**Comment by M1dKn1gh7** [comment]
Will do! It might be worth noting that had to explicitly specify both of these:


		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.2</version>
		</dependency>

		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>21.0</version>
		</dependency>

in my POM to get it to work but other than that we're good to go! Thanks again

**Comment by dmarcuse** [comment]
Hmm, interesting. In the [generated POM](https://bintray.com/apemanzilla/maven/edjournal/1.2.0-beta2#files/me%2Fapemanzilla%2Fedjournal%2F1.2.0-beta2) the scope for dependencies is specified as `<scope>runtime</scope>`, so they should be automatically pulled in for running/bundling, but not compiling.

**Comment by M1dKn1gh7** [comment]
Bit of odd behavior agreed but it's not a serious inconvenience as far as using it goes. I'm only just getting to grips with the implementation of the library. I like it!

 I see you have an EventType to handle unknowns. Is there a way of exposing the JSON after they are parsed? I'd like to use a lot of the data from the additional events in the game the library isn't aware of.

**Comment by dmarcuse** [comment]
Unfortunately not, one of the features I was considering but never implemented was having a `JournalEvent.json` field to store the original JSON. If you're up for implementing the missing/outdated events yourself, it should be relatively straightforward: you need to define/update the class extending `JournalEvent` (plenty of examples), and then register it in the map in `JournalEventDeserializer`. If you do update it, open a PR and I'll gladly merge it and publish a new version for it.

I'll look into implementing a way to access the raw JSON for events as well. IIRC the main reason I never got around to implementing it is that storing it as a `JsonObject` would expose gson classes despite it being an internal dependency, and storing it as a `String` is less useful.

**Comment by dmarcuse** [comment]
Considering how badly this needs an update, I may just use it as an excuse to get back into Elite: Dangerous and fix this up in the process.

**Comment by M1dKn1gh7** [comment]
Well I'm certainly not gonna complain about that! There are a few new event types but not a ton. And a JSON exposure would be useful anyway (unknown event or not). It's your code so of you'd prefer to fix it up yourself I understand but I'm more than happy to lend a hand :)

**Comment by M1dKn1gh7** [comment]
Also interstingly, I pushed the changes I needed to get my project to work and cloned my repo to my laptop today and the same failures have kicked in again which is a bit strange. I think there must be something screwy going on with the dependencies.

**Comment by dmarcuse** [comment]
I took a look at [what I presume is your project](https://github.com/M1dKn1gh7/EliteDangerousAssistantBackend), and while I'm not familiar with maven (I use gradle for everything) I don't see anywhere that you're adding the repository. If you click the "Set me up" button on [the bintray page](https://bintray.com/apemanzilla/maven/edjournal), it offers a sample - give that a shot and see if it helps?

**Comment by M1dKn1gh7** [comment]
Yeah the new profile in the Maven settings file (you won't see that in my project its just in ProgramFiles) 

I'd forgotten about that. That's done the trick. Two separate machines so they don't share config.

Once I play around with it a bit more I may look into into adding some new event types and exposing the JSON for any given event if the user wants it (particularly if it's unknown)
